/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface ImageData {
  id?: number;
  imageData?: Array<string>;
  name?: string;
  type?: string;
}
