/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { ImageData } from '../models/image-data';
import { Pret } from '../models/pret';
export interface Outil {
  categorieOutils?: 'CAT1' | 'CAT2';
  etat?: boolean;
  imageData?: ImageData;
  imgPath?: string;
  nom?: string;
  outilId?: number;
  prets?: Array<Pret>;
  videoPath?: string;
}
