/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { Outil } from '../models/outil';
import { User } from '../models/user';
export interface Pret {
  dateRetour?: string;
  outil?: Outil;
  pretId?: number;
  user?: User;
}
