/* tslint:disable */
/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { GrantedAuthority } from '../models/granted-authority';
import { Pret } from '../models/pret';
export interface User {
  accountNonExpired?: boolean;
  accountNonLocked?: boolean;
  addresse?: string;
  authorities?: Array<GrantedAuthority>;
  cotisation?: boolean;
  credentialsNonExpired?: boolean;
  dateAdh?: string;
  dateFinAdh?: string;
  email?: string;
  enabled?: boolean;
  name?: string;
  nom?: string;
  numTel?: string;
  password?: string;
  prenom?: string;
  prets?: Array<Pret>;
  role?: 'USER' | 'ADMIN';
  userId?: string;
  username?: string;
}
